server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelService
    username: postgres
    password: Elton@2897
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  config:
    import: optional:configserver:http://localhost:8085
    



