server:
  port: 8084

spring:
  application:
    name: HOTEL-API-GATEWAY
  config:
    import: optional:configserver:http://localhost:8085

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
           - Path=/user/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**,/Staff/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/**




